// ── API 에러 코드 ──────────────────────────────
// prefix_ACTION 형식

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_KAKAO_FAILED: 'AUTH_KAKAO_FAILED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_SIGNUP_REQUIRED: 'AUTH_SIGNUP_REQUIRED',

  // Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_INSUFFICIENT: 'PERMISSION_INSUFFICIENT',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_INVALID_INPUT: 'VALIDATION_INVALID_INPUT',

  // Member
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_NOT_APPROVED: 'MEMBER_NOT_APPROVED',
  MEMBER_SUSPENDED: 'MEMBER_SUSPENDED',
  MEMBER_NICKNAME_TAKEN: 'MEMBER_NICKNAME_TAKEN',

  // Reservation
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_SLOT_UNAVAILABLE: 'RESERVATION_SLOT_UNAVAILABLE',
  RESERVATION_MAX_PER_DAY: 'RESERVATION_MAX_PER_DAY',
  RESERVATION_HOLD_EXPIRED: 'RESERVATION_HOLD_EXPIRED',
  RESERVATION_HOLD_CONFLICT: 'RESERVATION_HOLD_CONFLICT',
  RESERVATION_INVALID_TRANSITION: 'RESERVATION_INVALID_TRANSITION',
  RESERVATION_CANCEL_DEADLINE: 'RESERVATION_CANCEL_DEADLINE',
  RESERVATION_DUPLICATE: 'RESERVATION_DUPLICATE',

  // Slot
  SLOT_NOT_FOUND: 'SLOT_NOT_FOUND',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  SLOT_HOLD_FAILED: 'SLOT_HOLD_FAILED',
  SLOT_ALREADY_HELD: 'SLOT_ALREADY_HELD',

  // Studio
  STUDIO_NOT_FOUND: 'STUDIO_NOT_FOUND',
  STUDIO_INACTIVE: 'STUDIO_INACTIVE',
  STUDIO_HAS_RESERVATIONS: 'STUDIO_HAS_RESERVATIONS',

  // Notification
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',

  // Settings
  SETTINGS_NOT_FOUND: 'SETTINGS_NOT_FOUND',
  SETTINGS_INVALID_VALUE: 'SETTINGS_INVALID_VALUE',

  // Fulfillment
  FULFILLMENT_NOT_FOUND: 'FULFILLMENT_NOT_FOUND',
  FULFILLMENT_INVALID_TRANSITION: 'FULFILLMENT_INVALID_TRANSITION',

  // Settlement
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',
  SETTLEMENT_INVALID_TRANSITION: 'SETTLEMENT_INVALID_TRANSITION',

  // Blackout
  BLACKOUT_CONFLICT: 'BLACKOUT_CONFLICT',
  BLACKOUT_NOT_FOUND: 'BLACKOUT_NOT_FOUND',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
